#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SanteDBAndroid.Resource", IsApplication=true)]

namespace SanteDBAndroid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SanteDB.DisconnectedClient.Android.Core.Resource.Id.contentFrame = global::SanteDBAndroid.Resource.Id.contentFrame;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.Layout.zxingscanneractivitylayout = global::SanteDBAndroid.Resource.Layout.zxingscanneractivitylayout;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.Layout.zxingscannerfragmentlayout = global::SanteDBAndroid.Resource.Layout.zxingscannerfragmentlayout;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.applet_confirm_close = global::SanteDBAndroid.Resource.String.applet_confirm_close;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.cancel = global::SanteDBAndroid.Resource.String.cancel;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.confirm = global::SanteDBAndroid.Resource.String.confirm;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_general = global::SanteDBAndroid.Resource.String.err_general;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_oauth2_invalid_client = global::SanteDBAndroid.Resource.String.err_oauth2_invalid_client;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_oauth2_invalid_grant = global::SanteDBAndroid.Resource.String.err_oauth2_invalid_grant;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_oauth2_invalid_request = global::SanteDBAndroid.Resource.String.err_oauth2_invalid_request;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_oauth2_invalid_scope = global::SanteDBAndroid.Resource.String.err_oauth2_invalid_scope;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_oauth2_unauthorized_client = global::SanteDBAndroid.Resource.String.err_oauth2_unauthorized_client;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_oauth2_unsupported_grant_type = global::SanteDBAndroid.Resource.String.err_oauth2_unsupported_grant_type;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_token_InvalidSignature = global::SanteDBAndroid.Resource.String.err_token_InvalidSignature;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_token_InvalidTokenType = global::SanteDBAndroid.Resource.String.err_token_InvalidTokenType;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_token_KeyNotFound = global::SanteDBAndroid.Resource.String.err_token_KeyNotFound;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_token_NotYetValid = global::SanteDBAndroid.Resource.String.err_token_NotYetValid;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.err_token_TokenExpired = global::SanteDBAndroid.Resource.String.err_token_TokenExpired;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.library_name = global::SanteDBAndroid.Resource.String.library_name;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.startup = global::SanteDBAndroid.Resource.String.startup;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.startup_configuration = global::SanteDBAndroid.Resource.String.startup_configuration;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.startup_data = global::SanteDBAndroid.Resource.String.startup_data;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.startup_setup = global::SanteDBAndroid.Resource.String.startup_setup;
			global::SanteDB.DisconnectedClient.Android.Core.Resource.String.startup_update = global::SanteDBAndroid.Resource.String.startup_update;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::SanteDBAndroid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::SanteDBAndroid.Resource.String.Hello;
			global::ZXing.Mobile.Resource.Id.contentFrame = global::SanteDBAndroid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::SanteDBAndroid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::SanteDBAndroid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F010000
			public const int horizontalSpacing = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int layout_breakLine = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int layout_horizontalSpacing = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int verticalSpacing = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int blue_gradient = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int circle_bg = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int gray_gradient = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int icon = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int logo = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int logo_lg = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int splash_gradient = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F030000
			public const int applet_view = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int contentFrame = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int txt_splash_info = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int txt_splash_version = 2130903043;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F040000
			public const int Applet = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int Splash = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int zxingscanneractivitylayout = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int zxingscannerfragmentlayout = 2130968579;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F050000
			public const int Icon = 2131034112;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F060002
			public const int activity_login = 2131099650;
			
			// aapt resource value: 0x7F060003
			public const int activity_setup = 2131099651;
			
			// aapt resource value: 0x7F060005
			public const int applet_confirm_close = 2131099653;
			
			// aapt resource value: 0x7F060000
			public const int ApplicationName = 2131099648;
			
			// aapt resource value: 0x7F060004
			public const int app_name = 2131099652;
			
			// aapt resource value: 0x7F060006
			public const int cancel = 2131099654;
			
			// aapt resource value: 0x7F060007
			public const int confirm = 2131099655;
			
			// aapt resource value: 0x7F060008
			public const int confirm_force_launch = 2131099656;
			
			// aapt resource value: 0x7F060009
			public const int err_applet_not_found = 2131099657;
			
			// aapt resource value: 0x7F06000A
			public const int err_exception = 2131099658;
			
			// aapt resource value: 0x7F06000B
			public const int err_general = 2131099659;
			
			// aapt resource value: 0x7F06000C
			public const int err_login = 2131099660;
			
			// aapt resource value: 0x7F06000D
			public const int err_login_invalidusername = 2131099661;
			
			// aapt resource value: 0x7F06000E
			public const int err_oauth2_invalid_client = 2131099662;
			
			// aapt resource value: 0x7F06000F
			public const int err_oauth2_invalid_grant = 2131099663;
			
			// aapt resource value: 0x7F060010
			public const int err_oauth2_invalid_request = 2131099664;
			
			// aapt resource value: 0x7F060011
			public const int err_oauth2_invalid_scope = 2131099665;
			
			// aapt resource value: 0x7F060012
			public const int err_oauth2_unauthorized_client = 2131099666;
			
			// aapt resource value: 0x7F060013
			public const int err_oauth2_unsupported_grant_type = 2131099667;
			
			// aapt resource value: 0x7F060014
			public const int err_online_required = 2131099668;
			
			// aapt resource value: 0x7F060015
			public const int err_startup = 2131099669;
			
			// aapt resource value: 0x7F060016
			public const int err_token_InvalidSignature = 2131099670;
			
			// aapt resource value: 0x7F060017
			public const int err_token_InvalidTokenType = 2131099671;
			
			// aapt resource value: 0x7F060018
			public const int err_token_KeyNotFound = 2131099672;
			
			// aapt resource value: 0x7F060019
			public const int err_token_NotYetValid = 2131099673;
			
			// aapt resource value: 0x7F06001A
			public const int err_token_TokenExpired = 2131099674;
			
			// aapt resource value: 0x7F060001
			public const int Hello = 2131099649;
			
			// aapt resource value: 0x7F06001B
			public const int installing_applets = 2131099675;
			
			// aapt resource value: 0x7F06001C
			public const int joinRealm = 2131099676;
			
			// aapt resource value: 0x7F06001D
			public const int leaveRealm = 2131099677;
			
			// aapt resource value: 0x7F06001E
			public const int library_name = 2131099678;
			
			// aapt resource value: 0x7F06001F
			public const int loading = 2131099679;
			
			// aapt resource value: 0x7F060020
			public const int login = 2131099680;
			
			// aapt resource value: 0x7F060021
			public const int login_title = 2131099681;
			
			// aapt resource value: 0x7F060022
			public const int needs_setup = 2131099682;
			
			// aapt resource value: 0x7F060023
			public const int noRealm = 2131099683;
			
			// aapt resource value: 0x7F060024
			public const int password = 2131099684;
			
			// aapt resource value: 0x7F060025
			public const int setting_log = 2131099685;
			
			// aapt resource value: 0x7F060026
			public const int setting_log_desc = 2131099686;
			
			// aapt resource value: 0x7F060027
			public const int setting_offline_only = 2131099687;
			
			// aapt resource value: 0x7F060028
			public const int setting_offline_only_desc = 2131099688;
			
			// aapt resource value: 0x7F060029
			public const int setup_subTitle = 2131099689;
			
			// aapt resource value: 0x7F06002A
			public const int setup_subTitle_app = 2131099690;
			
			// aapt resource value: 0x7F06002B
			public const int setup_subTitle_lnf = 2131099691;
			
			// aapt resource value: 0x7F06002C
			public const int setup_subTitle_sec = 2131099692;
			
			// aapt resource value: 0x7F06002D
			public const int setup_title = 2131099693;
			
			// aapt resource value: 0x7F06002E
			public const int setup_title_app = 2131099694;
			
			// aapt resource value: 0x7F06002F
			public const int setup_title_lnf = 2131099695;
			
			// aapt resource value: 0x7F060030
			public const int setup_title_sec = 2131099696;
			
			// aapt resource value: 0x7F060031
			public const int starting_services = 2131099697;
			
			// aapt resource value: 0x7F060032
			public const int startup = 2131099698;
			
			// aapt resource value: 0x7F060033
			public const int startup_configuration = 2131099699;
			
			// aapt resource value: 0x7F060034
			public const int startup_data = 2131099700;
			
			// aapt resource value: 0x7F060035
			public const int startup_setup = 2131099701;
			
			// aapt resource value: 0x7F060036
			public const int startup_update = 2131099702;
			
			// aapt resource value: 0x7F060037
			public const int user_name = 2131099703;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F070000
			public const int ActionBar = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int AppletTile = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int BlueTitle = 2131165186;
			
			// aapt resource value: 0x7F070003
			public const int DefaultFont = 2131165187;
			
			// aapt resource value: 0x7F070004
			public const int GrayTitle = 2131165188;
			
			// aapt resource value: 0x7F070005
			public const int SanteDB = 2131165189;
			
			// aapt resource value: 0x7F070006
			public const int SanteDB_NoTitle = 2131165190;
			
			// aapt resource value: 0x7F070007
			public const int SanteDB_Splash = 2131165191;
			
			// aapt resource value: 0x7F070008
			public const int SoftInputMode = 2131165192;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F010000,0x7F010003 }
			public static int[] FlowLayout = new int[] {
					2130771968,
					2130771971};
			
			// aapt resource value: 0
			public const int FlowLayout_horizontalSpacing = 0;
			
			// aapt resource value: { 0x7F010001,0x7F010002 }
			public static int[] FlowLayout_LayoutParams = new int[] {
					2130771969,
					2130771970};
			
			// aapt resource value: 0
			public const int FlowLayout_LayoutParams_layout_breakLine = 0;
			
			// aapt resource value: 1
			public const int FlowLayout_LayoutParams_layout_horizontalSpacing = 1;
			
			// aapt resource value: 1
			public const int FlowLayout_verticalSpacing = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F090000
			public const int file_paths = 2131296256;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
